#version: "3"
services:
  alloy:
    container_name: Grafana-Alloy
    hostname: Grafana-Alloy
    image: "grafana/alloy:latest"
    restart: unless-stopped
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
    ports:
      - 12345:12345
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: run --server.http.listen-addr=0.0.0.0:12345
        --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
