services:
  teamspeak-prometheus:
    image: teamspeak-prometheus:latest
    container_name: TeamSpeak-Prometheus
    hostname: TeamSpeak-Prometheus
    restart: unless-stopped
    networks:
      - teamspeak-network
      - back-tier
    environment:
      TEAMSPEAK_HOST: ${TEAMSPEAK_HOST}
      TEAMSPEAK_PORT: ${TEAMSPEAK_PORT}
    secrets:
      - TEAMSPEAK_USERNAME
      - TEAMSPEAK_PASSWORD
    ports:
      - 8002:8000
    command: >
      sh -c 'echo "Waiting for TeamSpeak Server on $TEAMSPEAK_HOST:$TEAMSPEAK_PORT..." &&
             while ! nc -z $TEAMSPEAK_HOST $TEAMSPEAK_PORT; do
               sleep 2
             done &&
             echo "TeamSpeak Server is up!" &&
             export TEAMSPEAK_USERNAME=$(cat /run/secrets/TEAMSPEAK_USERNAME) &&
             export TEAMSPEAK_PASSWORD=$(cat /run/secrets/TEAMSPEAK_PASSWORD) &&
             python app.py'

secrets:
  TEAMSPEAK_USERNAME:
    file: ${HOME}/.teamspeak/teamspeakusername.txt
  TEAMSPEAK_PASSWORD:
    file: ${HOME}/.teamspeak/teamspeakpassword.txt

networks:
  teamspeak-network:
    external: true
  back-tier:
    external: true
    name: internet-monitoring-back-tier
