#version: '3.5'
services:
  scrutiny:
    container_name: Scrutiny
    hostname: Scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    restart: unless-stopped
    cap_add:
      - SYS_RAWIO
    ports:
      - "8081:8080" # webapp
      - "8086:8086" # influxDB admin
    volumes:
      - /run/udev:/run/udev:ro
      - ${HOME}/.scrutiny/config:/opt/scrutiny/config
      - ${HOME}/.scrutiny/influxdb:/opt/scrutiny/influxdb
    devices:
      - "/dev/sda"
      - "/dev/sdb"
    environment:
      - COLLECTOR_CRON_SCHEDULE="0 3 * * *"
      - TZ=America/Los_Angeles
