services:
  portainer:
    image: portainer/portainer-ce
    container_name: Portainer
    hostname: Portainer
    restart: unless-stopped
    ports:
      - '8000:8000' # Edge compute features with Edge agents
      - '9443:9443' # WebUI
    volumes:
      - /var/lib/docker/volumes/portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
